import { Router } from 'express';
import empresaRoutes from './direction/empresaRoutes';
import personaRoutes from './direction/personaRoutes';
import usuarioRoutes from './direction/usuarioRoutes';
import actividadRoutes from './direction/actividadRoutes';
import historialRoutes from './direction/historialRoutes';
import authRoutes from './direction/authRoutes';
import cateringRoutes from './direction/cateringRoutes';
import cateringLoteRoutes from './direction/cateringLoteRoutes';
import postreRoutes from './direction/postreRoutes';
import loteRoutes from './direction/loteRoutes';
import ventaRoutes from './direction/ventaRoutes';
import cateringServiceRoutes from './direction/cateringServiceRoutes';
import recetaRoutes from './direction/recetaRoutes';
import ingredienteRoutes from './direction/ingredienteRoutes';
import categoriaRoutes from './direction/categoriaRoutes';
import productoCartaRoutes from './direction/productoCartaRoutes';
import serviceTipoRoutes from './direction/serviceTipoRoutes';

const router = Router();

router.use('/empresas', empresaRoutes);
router.use('/personas', personaRoutes);
router.use('/usuarios', usuarioRoutes);
router.use('/actividad', actividadRoutes);
router.use('/historial', historialRoutes);
router.use('/auth', authRoutes);
router.use('/catering-items', cateringRoutes);
router.use('/postres', postreRoutes);
router.use('/lotes', loteRoutes);
router.use('/ventas', ventaRoutes);
router.use('/catering-service', cateringServiceRoutes);
router.use('/recetas', recetaRoutes);
router.use('/ingredientes', ingredienteRoutes);
router.use('/catering-lotes', cateringLoteRoutes);
router.use('/categorias', categoriaRoutes);
router.use('/productos-carta', productoCartaRoutes);
router.use('/service-tipos', serviceTipoRoutes);

export default router;